# Site settings
title: Hello
description: 'for record' # this means to ignore newlines until "baseurl:"
permalink: '/year/month/day/title'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://Dipif.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/long-short.png"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "manual"

logo-dark: "/assets/img/branding/long-short.png"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: 이대겸 # add your name
author-pic: "/profile_image.jpg"
about-author: 안녕하세요. 2022년 졸업 예정입니다. 현재 프로그래머스의 AI 데브코스를 수강 중입니다.


# Contact links
email: dipif361@gmail.com # Add your Email address
website: https://dipif.github.io # Add your website
github: Dipif # Add your Github handle

# Disqus
# Tracker

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]